config/routes.rb
Phcaccounts::Engine.routes.draw do

  # Dashboard Routes
  get 'welcome_status_page', to: 'accounts/dashboard#index'

  # Administrative Routes
  namespace :admin do
    resources :users
  end

  get 'admin_users_all', to: 'admin/accounts#index'

  # Devise routes
  devise_for :users, class_name: "Phcaccounts::User", module: :devise

end

app/models/phcaccounts/admin.rb
module Phcaccounts
  module Admin
  end
end

app/models/phcaccounts/admin/user.rb
module Phcaccounts
  class Admin::User < ApplicationRecord
  end
end

app/models/phcaccounts/application_record.rb
module Phcaccounts
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/phcaccounts/user.rb
module Phcaccounts
  class User < ApplicationRecord

    # Autogenerate Organization ID
    before_create :phc_devise_generate_org_id

    # User Gravatar Support
    include Gravtastic
    gravtastic

    # Add Users Roles
    enum role: [:user, :editor, :admin]
    after_initialize :phc_set_default_role

    # Include default devise modules. Others available are:
    # :confirmable, :lockable and :omniauthable
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :timeoutable

    private

    # Autogenerate User Organization ID
    def phc_devise_generate_org_id
      self.org_id = SecureRandom.hex(5)
    end

    # First Signup Admin and Rest Default to User
    def phc_set_default_role
      if User.all.count < 1
        self.role ||= :admin
      else
        self.role ||= :user
      end
    end

  end
end

app/controllers/phcaccounts/accounts/dashboard_controller.rb
require_dependency "phcaccounts/application_controller"

module Phcaccounts
  class Accounts::DashboardController < ApplicationController

    # Include Core Helpers, Security & Action Filters
    include Phccorehelpers::PhcpluginsproHelper
    before_action :authenticate_user!

    # Index Dashboard
    def index
    end

  end
end

app/controllers/phcaccounts/admin/users_controller.rb
require_dependency "phcaccounts/application_controller"

module Phcaccounts
  class Admin::UsersController < ApplicationController

    # Include Core Helpers, Security & Action Filters
    include Phccorehelpers::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :phc_accounts_admin_only

    # INDEX
    def index
      @admin_users = Phcaccounts::User.all
    end

    # DETAILS
    def show
    end

    # NEW
    def new
      @admin_user = Admin::User.new
    end

    # GET /admin/users/1/edit
   def edit
     @admin_user = Phcaccounts::User.find(params[:id])
   end

    # POST /admin/users
    def create
      @admin_user = Phcaccounts::User.find(params[:id])
      if @admin_user.save
        redirect_to admin_users_path, notice: 'User information was successfully created.'
      else
        render :new
      end
    end

    # UPDATE
   def update
     @admin_user = Phcaccounts::User.find(params[:id])
     if @admin_user.update
        redirect_to admin_users_path, notice: 'User information was successfully updated.'
     else
       render 'edit'
     end
   end

    # DELETE /admin/users/1
    def destroy
      @admin_user = Phcaccounts::User.find(params[:id])
      @admin_user.destroy
      redirect_to admin_users_path, notice: 'User information was successfully delted.'
    end

    private

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

  end
end

app/controllers/phcaccounts/application_controller.rb
module Phcaccounts
    class ApplicationController < ActionController::Base

      # Devise Filter
      before_action :phc_accounts_permitted_parameters, if: :devise_controller?

      # Security Filters
      protect_from_forgery with: :exception

      # Load Requried Helper Files
      helper Phccorehelpers::Engine.helpers
      helper Phcmenus::Engine.helpers
      helper Phctitleseo::Engine.helpers
      helper Phcnotifi::Engine.helpers

      private

      # Whitelist Additional Fields
      def phc_accounts_permitted_parameters
        added_attrs = [:username, :firstname, :lastname, :email, :terms_of_service, :password, :password_confirmation, :remember_me]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      end

      # Redirect User to Root After Login
      def after_sign_in_path_for(resource)
        main_app.root_path
      end

    end
end

app/helpers/phcaccounts/accounts/dashboard_helper.rb
module Phcaccounts
  module Accounts::DashboardHelper
  end
end

app/helpers/phcaccounts/admin/accounts_helper.rb
module Phcaccounts
  module Admin::AccountsHelper
  end
end

app/helpers/phcaccounts/admin/users_helper.rb
module Phcaccounts
  module Admin::UsersHelper
  end
end

app/helpers/phcaccounts/application_helper.rb
module Phcaccounts
  module ApplicationHelper
  end
end

app/views/layouts/phcaccounts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <!-- SEO System -->
  <% phc_seo_title "PHCAccounts by PHCDevworks" %>
  <% phc_seo_description "Rails Authentication and User Management Engine." %>
  <!-- SEO System -->

  <!-- SEO and Site Description -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title><%= yield(:phc_seo_title) %></title>
  <meta name="description" content="<%= yield(:phc_seo_description) %>">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <link rel="canonical" href="http://phcdevworks.com">
  <!-- SEO and Site Description -->

  <!-- Rails Security Tags -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Rails Security Tags -->

  <!-- CSS Styles -->
  <%= stylesheet_link_tag 'phcaccounts/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- CSS Styles -->

  <!-- Font -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700"/>
  <!-- Font -->

</head>
<body>

  <!-- Page Container -->
  <div id="page-container" class="page-container fade page-sidebar-fixed page-header-fixed">

    <!-- Page Header -->
    <div id="header" class="header navbar-default">
      <%= render 'layouts/phcaccounts/components/backend/navigation/top_menu' %>
    </div>
    <!-- Page Header -->

    <!-- Page Sidebar -->
    <div id="sidebar" class="sidebar">
      <%= render 'layouts/phcaccounts/components/backend/sidebars/side_menu' %>
    </div>
    <div class="sidebar-bg"></div>
    <!-- Page Sidebar -->

    <!-- Page Content -->
    <div id="content" class="content">
      <%= yield %>
    </div>
    <!-- Page Content -->

    <!-- Footer Content -->
    <div id="footer" class="footer mb-4">
      <%= render 'layouts/phcaccounts/components/backend/footer/footer' %>
    </div>
    <!-- Footer Content -->

  </div>
  <!-- Page Container -->

  <!-- JavaScript -->
  <%= javascript_include_tag "phcaccounts/application", 'data-turbolinks-track': 'reload' %>
  <!-- JavaScript -->

  <!-- JavaScript Loader -->
  <script>
    $(document).ready(function() {
      App.init();
    });
  </script>
  <!-- JavaScript Loader -->

</body>
</html>

app/views/layouts/phcaccounts/application_full_width.html.erb
<!DOCTYPE html>
<html>
<head>

  <!-- SEO System -->
  <% phc_seo_title "PHCAccounts by PHCDevworks" %>
  <% phc_seo_description "Rails Authentication and User Management Engine." %>
  <!-- SEO System -->

  <!-- SEO and Site Description -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title><%= yield(:phc_seo_title) %></title>
  <meta name="description" content="<%= yield(:phc_seo_description) %>">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <link rel="canonical" href="http://phcdevworks.com">
  <!-- SEO and Site Description -->

  <!-- Rails Security Tags -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Rails Security Tags -->

  <!-- CSS Styles -->
  <%= stylesheet_link_tag 'phcaccounts/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- CSS Styles -->

  <!-- Font -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700"/>
  <!-- Font -->

</head>
<body>

  <!-- Page Container -->
  <div id="page-container" class="page-container fade page-sidebar-fixed page-header-fixed">

    <!-- Page Header -->
    <div id="header" class="header navbar-default">
      <%= render 'layouts/phcaccounts/components/backend/navigation/top_menu' %>
    </div>
    <!-- Page Header -->

    <!-- Page Sidebar -->
    <div id="sidebar" class="sidebar">
      <%= render 'layouts/phcaccounts/components/backend/sidebars/side_menu' %>
    </div>
    <div class="sidebar-bg"></div>
    <!-- Page Sidebar -->

    <!-- Page Content -->
    <div id="content" class="content content-full-width">
      <%= render 'phcnotifi/default/notifications' %>
      <%= yield %>
    </div>
    <!-- Page Content -->

    <!-- Footer Content -->
    <div id="footer" class="footer mb-4">
      <%= render 'layouts/phcaccounts/components/backend/footer/footer' %>
    </div>
    <!-- Footer Content -->

  </div>
  <!-- Page Container -->

  <!-- JavaScript -->
  <%= javascript_include_tag "phcaccounts/application", 'data-turbolinks-track': 'reload' %>
  <!-- JavaScript -->

  <!-- JavaScript Loader -->
  <script>
    $(document).ready(function() {
      App.init();
    });
  </script>
  <!-- JavaScript Loader -->

</body>
</html>

app/views/layouts/phcaccounts/application_no_sidebar.html.erb
<!DOCTYPE html>
<html>
<head>

  <!-- SEO System -->
  <% phc_seo_title "PHCAccounts by PHCDevworks" %>
  <% phc_seo_description "Rails Authentication and User Management Engine." %>
  <!-- SEO System -->

  <!-- SEO and Site Description -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title><%= yield(:phc_seo_title) %></title>
  <meta name="description" content="<%= yield(:phc_seo_description) %>">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <link rel="canonical" href="http://phcdevworks.com">
  <!-- SEO and Site Description -->

  <!-- Rails Security Tags -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Rails Security Tags -->

  <!-- CSS Styles -->
  <%= stylesheet_link_tag 'phcaccounts/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- CSS Styles -->

  <!-- Font -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700"/>
  <!-- Font -->

</head>
<body>

  <!-- Page Container -->
  <div id="page-container" class="fade page-without-sidebar page-header-fixed">

    <!-- Page Header -->
    <div id="header" class="header navbar-default">
      <%= render 'layouts/phcaccounts/components/backend/navigation/top_menu' %>
    </div>
    <!-- Page Header -->

    <!-- Page Content -->
    <div id="content" class="content">
      <%= render 'phcnotifi/default/notifications' %>
      <%= yield %>
    </div>
    <!-- Page Content -->

    <!-- Footer Content -->
    <div id="footer" class="footer mb-4">
      <%= render 'layouts/phcaccounts/components/backend/footer/footer' %>
    </div>
    <!-- Footer Content -->

  </div>
  <!-- Page Container -->

  <!-- JavaScript -->
  <%= javascript_include_tag "phcaccounts/application", 'data-turbolinks-track': 'reload' %>
  <!-- JavaScript -->

  <!-- JavaScript Loader -->
  <script>
    $(document).ready(function() {
      App.init();
    });
  </script>
  <!-- JavaScript Loader -->

</body>
</html>

app/views/layouts/phcaccounts/components/backend/footer/_footer.html.erb
<span class="float-left">
  2012-<%= Time.now.year %> -
  <strong>PHC</strong>Accounts -
  Engine v<%= Gem.loaded_specs["phcaccounts"].version.to_s %>
</span>
<span class="float-right">
  Developed with <i class="fas fa-heart hanna_hearts"></i> by
  <a class="phcnet_copyright" href="https://phcdevworks.com/"><strong>PHC</strong>Devworks</a>
</span>

app/views/layouts/phcaccounts/components/backend/navigation/_top_menu.html.erb
<!-- Topbar - Navigation Header -->
<div class="navbar-header">
  <%= link_to phcaccounts.welcome_status_page_path, class: "navbar-brand" do %>
    <strong>PHC</strong>Accounts
  <% end %>
  <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>
<!-- Topbar - Navigation Header -->

<!-- Topbar - Navigation Main -->
<% if current_user %>
  <ul class="navbar-nav navbar-right">

    <!-- Topbar - Navigation Main - User Menu -->
    <li class="dropdown navbar-user">
      <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
        <%= image_tag current_user.gravatar_url %>
        <span class="d-none d-md-inline"><%= current_user.firstname + ' ' + current_user.lastname  %></span> <b class="caret"></b>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <%= link_to phcaccounts.edit_user_registration_path, class: "dropdown-item" do %>
          <i class="fas fa-cogs"></i> Account Settings
        <% end %>
        <%= link_to phcaccounts.destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
          <i class="fas fa-sign-out-alt"></i> Logout
        <% end %>
      </div>
    </li>
    <!-- Topbar - Navigation Main - User Menu -->

  </ul>
<% end %>
<!-- Topbar - Navigation Main -->

app/views/layouts/phcaccounts/devise.html.erb
<!DOCTYPE html>
<html>
<head>

  <!-- SEO System -->
  <% phc_seo_title "PHCAccounts by PHCDevworks" %>
  <% phc_seo_description "Rails Authentication and User Management Engine." %>
  <!-- SEO System -->

  <!-- SEO and Site Description -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title><%= yield(:phc_seo_title) %></title>
  <meta name="description" content="<%= yield(:phc_seo_description) %>">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <link rel="canonical" href="http://phcdevworks.com">
  <!-- SEO and Site Description -->

  <!-- Rails Security Tags -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Rails Security Tags -->

  <!-- CSS Styles -->
  <%= stylesheet_link_tag 'phcaccounts/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- CSS Styles -->

  <!-- Font -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700"/>
  <!-- Font -->

</head>
<body class="pace-top bg-white">

  <!-- Page Content -->
  <%= render 'phcnotifi/default/notifications' %>
  <%= yield %>
  <!-- Page Content -->

  <!-- JavaScript -->
  <%= javascript_include_tag "phcaccounts/application", 'data-turbolinks-track': 'reload' %>
  <!-- JavaScript -->

  <!-- JavaScript Loader -->
  <script>
    $(document).ready(function() {
      App.init();
    });
  </script>
  <!-- JavaScript Loader -->

</body>
</html>

app/views/phcaccounts/admin/users/_form.html.erb
<%= form_with(model: @admin_user, url: registration_path(resource_name)) do |form| %>

	<!-- PHCNotifi Render Validation -->
	<%= render 'phcnotifi/default/validations', :object => @admin_user %>
	<!-- PHCNotifi Render Validation -->

	<div class="form-group">
		<%= form.label :firstname, "First Name" %>
		<%= form.text_field :firstname, class: "form-control", placeholder: "First Name" %>
	</div>

	<div class="form-group">
		<%= form.label :lastname, "Last Name" %>
		<%= form.text_field :lastname, class: "form-control", placeholder: "Last Name" %>
	</div>

	<div class="form-group">
		<%= form.label :username, "User Name" %>
		<%= form.text_field :username, class: "form-control", placeholder: "User Name" %>
	</div>

	<div class="form-group">
		<%= form.label :email %>
		<%= form.email_field :email, class: "form-control", placeholder: "Email Address", autofocus: true %>
	</div>

	<div class="form-group">
		<%= form.label :password, "New Password" %> <i>(leave blank if you don't want to change it)</i>
		<%= form.password_field :password, class: "form-control", placeholder: "New Password", autocomplete: "off" %>
	</div>

	<div class="form-group">
		<%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm New Password", autocomplete: "off" %>
	</div>

	<% if @minimum_password_length %>
		<h6>Password (minimum <%= @minimum_password_length %> characters.)</h6>
	<% end %>

	<div class="actions">
		<%= form.submit "Update", class: "btn btn-w-m btn-primary" %>
	</div>

<% end %>

app/views/phcaccounts/admin/users/edit.html.erb
<!-- Title System -->
<% phc_title "User Manager" %>
<% phc_title_tagline "Edit User" %>
<% phc_breadcrumb_one link_to "Home", main_app.root_path %>
<% phc_breadcrumb_two link_to "User List", phcaccounts.admin_users_path %>
<% phc_breadcrumb_three yield(:phc_title_tagline) %>
<!-- Title System -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_two) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_three) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h1 class="page-header"><%= yield(:phc_title) %></h1>
<!-- Page Header -->

<!-- Page Content -->
<div class="panel panel-inverse">
	<div class="panel-heading">
		<div class="panel-heading-btn">
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
		</div>
		<h4 class="panel-title"><%= yield(:phc_title) %></h4>
	</div>
	<div class="panel-body">

		<!-- Form for User Update -->
		<%= render 'form', { form_url: admin_user_path } %>
		<!-- Form for User Update -->

	</div>
</div>
<!-- Page Content -->

app/views/phcaccounts/admin/users/index.html.erb
<!-- Title System -->
<% phc_title "User Manager" %>
<% phc_title_tagline "User List" %>
<% phc_breadcrumb_one link_to "Home", main_app.root_path %>
<% phc_breadcrumb_two link_to "Accounts Info", phcaccounts.welcome_status_page_path %>
<% phc_breadcrumb_three yield(:phc_title_tagline) %>
<!-- Title System -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_two) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_three) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h1 class="page-header"><%= yield(:phc_title) %></h1>
<!-- Page Header -->

<!-- Page Content -->
<div class="panel panel-inverse">
	<div class="panel-heading">
		<div class="panel-heading-btn">
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
		</div>
		<h4 class="panel-title"><%= yield(:phc_title_tagline) %></h4>
	</div>
	<div class="panel-body">

		<!-- Table - User Index -->
		<div class="table-responsive">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>User ID</th>
						<th>Username</th>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Email</th>
					</tr>
				</thead>
				<tbody>
					<% @admin_users.each do |phc_accounts_admin_user_index| %>
						<tr>
							<td><%= phc_accounts_admin_user_index.id %></td>
							<td><%= phc_accounts_admin_user_index.username %></td>
							<td><%= phc_accounts_admin_user_index.firstname %></td>
							<td><%= phc_accounts_admin_user_index.lastname %></td>
							<td><%= phc_accounts_admin_user_index.email %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<!-- Table - User Index -->

	</div>
</div>
<!-- Page Content -->

app/views/phcaccounts/admin/users/new.html.erb
<!-- Title System -->
<% phc_title "User Manager" %>
<% phc_title_tagline "New User" %>
<% phc_breadcrumb_one link_to "Home", main_app.root_path %>
<% phc_breadcrumb_two link_to "User List", phcaccounts.admin_users_path %>
<% phc_breadcrumb_three yield(:phc_title_tagline) %>
<!-- Title System -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_two) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_three) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h1 class="page-header"><%= yield(:phc_title) %></h1>
<!-- Page Header -->

<!-- Page Content -->
<div class="panel panel-inverse">
	<div class="panel-heading">
		<div class="panel-heading-btn">
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
			<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
		</div>
		<h4 class="panel-title"><%= yield(:phc_title) %></h4>
	</div>
	<div class="panel-body">

		<!-- Form for New User -->
		<%= render 'form', { form_url: admin_user_path } %>
		<!-- Form for New User -->

	</div>
</div>
<!-- Page Content -->

app/views/phcaccounts/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  Already a member? Click <%= link_to "Here", new_session_path(resource_name) %> to login.</br>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  Not a member yet? Click <%= link_to "here", new_registration_path(resource_name) %> to register.</br>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %></br>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %></br>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>